# Generated by Django 4.1.4 on 2024-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=2)),
                ('stock', models.CharField(max_length=2)),
                ('activo_zeus', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('fecha_inicial', models.CharField(max_length=50)),
                ('fecha_final', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('id_sede', models.CharField(max_length=50)),
                ('regimen', models.CharField(max_length=50)),
                ('activo', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoAtencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_zeus', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=10)),
                ('Municipio', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadFuncional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_zeus', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('id_sede', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
