# Generated by Django 4.1.4 on 2024-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0002_rename_municipio_puntoatencion_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_zeus', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
