# Generated by Django 4.1.4 on 2024-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0003_alter_contrato_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacion',
            field=models.CharField(max_length=500),
        ),
    ]
