# Generated by Django 4.1.4 on 2024-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0005_alter_contrato_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
