# Generated by Django 4.1.4 on 2024-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0006_alter_contrato_empresa_alter_contrato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
