# Generated by Django 4.1.4 on 2024-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0007_alter_contrato_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
