# Generated by Django 4.1.4 on 2024-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0008_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioZeus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_zeus', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
