# Generated by Django 4.1.4 on 2024-10-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_actividad_usuario_zeus'),
        ('zeus_mirror', '0012_alter_usuariozeus_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioZeus',
        ),
    ]
