# Generated by Django 4.1.4 on 2025-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0013_delete_usuariozeus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('desplegable', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
