# Generated by Django 4.1.4 on 2025-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0014_finalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalidad',
            name='valor',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
