# PARÁMETROS GENERALES

CODIGO_MEDICO = 1
NOMBRE_USUARIO = "LUIS FERNANDO RODRIGUEZ"
NUMERO_USUARIO = 1
IDENTIFICACION_USUARIO = "1047394846"
TIPO_DIAGNOSTICO = 1
CODIGO_ENTIDAD = {
    "Contributivo": "EPS048",
    "Subsidiado":"ESS207"
}