# Generated by Django 4.1.4 on 2024-08-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zeus_mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento_paciente', models.IntegerField()),
                ('numero_estudio', models.IntegerField()),
                ('json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaPrograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoMarco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato_contributivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributivo', to='zeus_mirror.contrato')),
                ('contrato_subsidiado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidado', to='zeus_mirror.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regional', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cups', models.CharField(max_length=10)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=10, null=True)),
                ('finalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True)),
                ('entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.contratomarco')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosAreaPrograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.areaprograma')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.centrocosto')),
                ('punto_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.puntoatencion')),
                ('regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.regional')),
                ('sede', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.sede')),
                ('unidad_funcional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.unidadfuncional')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_fuente', models.CharField(max_length=10)),
                ('identificador', models.CharField(max_length=150)),
                ('regional', models.CharField(max_length=150)),
                ('fecha_servicio', models.DateField()),
                ('nombre_actividad', models.CharField(max_length=250)),
                ('diagnostico_p', models.CharField(default='', max_length=10)),
                ('diagnostico_1', models.CharField(default='', max_length=10)),
                ('diagnostico_2', models.CharField(default='', max_length=10)),
                ('diagnostico_3', models.CharField(default='', max_length=10)),
                ('tipo_documento', models.CharField(default='CC', max_length=10)),
                ('documento_paciente', models.CharField(max_length=50)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.admision')),
                ('parametros_programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.parametrosareaprograma')),
                ('tipo_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tipoactividad')),
            ],
        ),
    ]
