# Generated by Django 4.1.4 on 2024-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('cups', models.CharField(max_length=10)),
                ('responsable', models.CharField(max_length=150)),
                ('diagnostico', models.CharField(max_length=10)),
                ('finalidad', models.CharField(max_length=50)),
                ('fuente', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=150)),
                ('entrega', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
