# Generated by Django 4.1.4 on 2024-08-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=150)),
                ('tipo_fuente', models.CharField(max_length=10)),
                ('fecha_servicio', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('diagnostico_p', models.CharField(max_length=10)),
                ('diagnostico_1', models.CharField(max_length=10)),
                ('diagnostico_2', models.CharField(max_length=10)),
                ('diagnostico_3', models.CharField(max_length=10)),
                ('documento_paciente', models.CharField(max_length=50)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('embarazo', models.CharField(max_length=150)),
                ('sede', models.CharField(max_length=150)),
                ('punto_atencion', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tipoactividad')),
            ],
        ),
    ]
