# Generated by Django 4.1.4 on 2024-08-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0002_rename_municipio_puntoatencion_municipio'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosareaprograma',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.centrocosto'),
        ),
        migrations.AlterField(
            model_name='parametrosareaprograma',
            name='punto_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.puntoatencion'),
        ),
        migrations.AlterField(
            model_name='parametrosareaprograma',
            name='unidad_funcional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.unidadfuncional'),
        ),
    ]
