# Generated by Django 4.1.4 on 2024-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='finalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
