# Generated by Django 4.1.4 on 2024-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tipoactividad_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='identificador',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
