# Generated by Django 4.1.4 on 2024-08-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='regional',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.areaprograma'),
        ),
    ]
