# Generated by Django 4.1.4 on 2024-08-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0004_rename_codigo_sede_ciudad_and_more'),
        ('home', '0003_areaprograma_regional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='punto_atencion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='unidad_funcional',
        ),
        migrations.AddField(
            model_name='actividad',
            name='parametros_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.parametrosareaprograma'),
        ),
        migrations.AddField(
            model_name='parametrosareaprograma',
            name='sede',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.sede'),
        ),
        migrations.AlterField(
            model_name='parametrosareaprograma',
            name='area_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.areaprograma'),
        ),
        migrations.AlterField(
            model_name='parametrosareaprograma',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.regional'),
        ),
    ]
