# Generated by Django 4.1.4 on 2024-08-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_colaborador_regional_colaborador_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='area',
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.areaprograma'),
        ),
    ]
