# Generated by Django 4.1.4 on 2024-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_actividad_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=10),
        ),
    ]
