# Generated by Django 4.1.4 on 2024-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contratomarco'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomarco',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contratomarco',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
