# Generated by Django 4.1.4 on 2024-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_actividad_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='unidad_funcional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='numero_contrato',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='tipo_servicio',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='punto_atencion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='sede',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
