# Generated by Django 4.1.4 on 2024-08-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.carga'),
        ),
    ]
