# Generated by Django 4.1.4 on 2024-08-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contratomarco_observacion_alter_contratomarco_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoactividad',
            name='contrato',
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidado', to='home.contratomarco'),
        ),
    ]
