# Generated by Django 4.1.4 on 2024-08-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0005_tiposervicio'),
        ('home', '0007_remove_tipoactividad_contrato_tipoactividad_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.contratomarco'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.tiposervicio'),
        ),
    ]
