# Generated by Django 4.1.4 on 2024-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_actividad_diagnostico_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('cups', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='numero_contrato',
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='contrato',
            field=models.ManyToManyField(to='home.contrato'),
        ),
    ]
