# Generated by Django 4.1.4 on 2024-08-30 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_actividad_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='carga',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
