# Generated by Django 4.1.4 on 2024-08-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_carga_colaborador_carga_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='estado',
            field=models.CharField(choices=[(0, 'eliminada'), (1, 'creada'), (2, 'procesada')], default=1, max_length=1),
        ),
    ]
