# Generated by Django 4.1.4 on 2024-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contrato_remove_tipoactividad_numero_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero_contrato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
