# Generated by Django 4.1.4 on 2024-08-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contrato_numero_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cups',
        ),
    ]
