# Generated by Django 4.1.4 on 2024-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_tipoactividad_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
