# Generated by Django 4.1.4 on 2024-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_carga_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cantidad_actividades',
            field=models.IntegerField(default=0),
        ),
    ]
