# Generated by Django 4.1.4 on 2024-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contrato_cups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='contrato',
            field=models.ManyToManyField(related_name='contratos', to='home.contrato'),
        ),
    ]
