# Generated by Django 4.1.4 on 2024-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_carga_cantidad_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='estado',
            field=models.CharField(choices=[('eliminada', 'Carga eliminada'), ('creada', 'Carga creada'), ('procesada', 'Carga procesada')], default='creada', max_length=10),
        ),
    ]
