# Generated by Django 4.1.4 on 2024-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_tipoactividad_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='regimen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
