# Generated by Django 4.1.4 on 2024-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_carga_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='inconsistencias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
