# Generated by Django 4.1.4 on 2024-09-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_actividad_inconsistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='tiempo_procesamiento',
            field=models.FloatField(default=0),
        ),
    ]
