# Generated by Django 4.1.4 on 2024-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_carga_cantidad_actividades_inconsistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cantidad_actividades_ok',
            field=models.IntegerField(default=0),
        ),
    ]
