# Generated by Django 4.1.4 on 2024-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_carga_cantidad_actividades_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cantidad_actividades_admisionadas',
            field=models.IntegerField(default=0),
        ),
    ]
