# Generated by Django 4.1.4 on 2024-09-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_actividad_inconsistencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
