# Generated by Django 4.1.4 on 2024-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='medico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
