# Generated by Django 4.1.4 on 2024-10-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0008_medico'),
        ('home', '0022_actividad_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.medico'),
        ),
    ]
