# Generated by Django 4.1.4 on 2024-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_actividad_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='estado',
            field=models.CharField(choices=[('eliminada', 'Carga eliminada'), ('creada', 'Carga creada'), ('procesando', 'Carga en proceso'), ('procesada', 'Carga procesada'), ('admisionando', 'Carga en proceso de creación de admisiones'), ('cancelada', 'Carga presentó errores durante su procesamiento')], default='creada', max_length=20),
        ),
    ]
