# Generated by Django 4.1.4 on 2024-10-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_actividad_usuario_zeus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='usuario_zeus',
        ),
    ]
