# Generated by Django 4.1.4 on 2024-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_actividad_usuario_zeus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenApiZeus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=250)),
                ('vigente', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
