# Generated by Django 4.1.4 on 2024-11-01 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_tokenapizeus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenapizeus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
