# Generated by Django 4.1.4 on 2024-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_actividad_datos_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='admisionada_otra_carga',
            field=models.BooleanField(default=False),
        ),
    ]
