# Generated by Django 4.1.4 on 2024-12-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_actividad_admisionada_otra_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='num_tareas_en_proceso',
            field=models.IntegerField(default=0),
        ),
    ]
