# Generated by Django 4.1.4 on 2025-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_actividad_documento_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre_paciente',
            field=models.CharField(max_length=200),
        ),
    ]
