# Generated by Django 4.1.4 on 2025-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_carga_observacion_alter_actividad_nombre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='diagnostico_1',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='diagnostico_2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='diagnostico_3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='diagnostico_p',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='identificador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_fuente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
