# Generated by Django 4.1.4 on 2025-01-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_actividad_nombre_paciente'),
        ('home', '0034_carga_observacion_alter_actividad_nombre_paciente'),
    ]

    operations = [
    ]
