# Generated by Django 4.1.4 on 2025-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_actividad_diagnostico_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_fuente',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
