# Generated by Django 4.1.4 on 2025-04-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_actividad_tipo_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
