# Generated by Django 4.1.4 on 2025-04-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_merge_20250121_1118'),
        ('home', '0036_alter_actividad_tipo_fuente'),
    ]

    operations = [
    ]
