# Generated by Django 4.1.4 on 2025-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_admision_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
