# Generated by Django 4.1.4 on 2025-04-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_admision_observacion'),
        ('home', '0037_merge_20250407_1203'),
    ]

    operations = [
    ]
