# Generated by Django 4.1.4 on 2025-05-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_actividad_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
