# Generated by Django 4.1.4 on 2025-05-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_merge_20250422_1345'),
        ('home', '0039_alter_actividad_tipo_usuario'),
    ]

    operations = [
    ]
