# Generated by Django 4.1.4 on 2025-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_actividad_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='observacion',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
