# Generated by Django 4.1.4 on 2025-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_admision_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
