# Generated by Django 4.1.4 on 2025-05-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0014_finalidad'),
        ('home', '0041_alter_admision_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactividad',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.finalidad'),
        ),
    ]
