# Generated by Django 4.1.4 on 2025-05-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeus_mirror', '0014_finalidad'),
        ('home', '0042_alter_tipoactividad_finalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='finalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zeus_mirror.finalidad'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='finalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
