# Generated by Django 4.1.4 on 2025-05-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_merge_20250514_0939'),
        ('home', '0043_actividad_finalidad_alter_tipoactividad_finalidad'),
    ]

    operations = [
    ]
