# Generated by Django 4.1.4 on 2026-04-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_merge_20250522_1141'),
        ('home', '0045_actividad_contrato'),
    ]

    operations = [
    ]
