# Generated by Django 4.1.4 on 2026-04-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_backfill_actividad_contrato'),
        ('home', '0046_merge_20260415_1546'),
    ]

    operations = [
    ]
