# Generated by Django 4.1.4 on 2026-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_merge_20260423_1213'),
        ('home', '0047_normalize_regimen_inconsistente_message'),
    ]

    operations = [
    ]
