# Generated by Django 4.1.4 on 2026-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_merge_20260511_0956'),
        ('home', '0048_normalize_tipo_usuario_inconsistencia'),
    ]

    operations = [
    ]
