"""
Django settings for inzeusagilad project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from __future__ import absolute_import, unicode_literals

from pathlib import Path

from django.conf import settings

# from unipath import Path
import os

from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  config('DEBUG', cast = bool)
ALLOWED_HOSTS=(config('ALLOWED_HOSTS')).split(",")
CSRF_TRUSTED_ORIGINS = (config('CSRF_TRUSTED_ORIGINS')).split(",")

# URL del API de ZEUS
URL_API_ZEUS = config('URL_API_ZEUS')
URL_API_ZEUS_PRUEBA = config('URL_API_ZEUS_PRUEBA')

print(ALLOWED_HOSTS)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'zeus_mirror',
    'home', 
    'django_q' 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zagilad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zagilad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': config('ENGINE'),
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASS'),
        'HOST': config('HOST'),
        'PORT': config('PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Extra places for collectstatic to find static files.
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#############################################################
#############################################################

FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 # 10 Mb limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 # 20 Mb limit

EMAIL_BACKEND =  config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')


USUARIO_API_ZEUS = config('USUARIO_API_ZEUS')
PASSWORD_API_ZEUS = config('PASSWORD_API_ZEUS')


Q_CLUSTER = {
    'name': config('NAME_CLUSTER'),
    # 8 workers reducido desde 30: el SQL Server interno de ZEUS no banca
    # 30 INSERTs concurrentes sobre ingresos/ingresos_servicios y se ven
    # >20% de deadlocks. Con 8 la contención cae fuerte y cargue local
    # sigue siendo lo bastante paralelo (es CPU/IO local, no remoto).
    'workers': 8,
    'recycle': 500,
    'timeout': 72000,
    'retry':72200,
    'bulk': 10,
    # 'queue_limit': 5,
    # 'cpu_affinity': 1,
    'save_limit': 250,
    'orm': 'default',
}

# Lote dinámico para tareas de admisionado: apunta a generar
# ~ADMISIONADO_TARGET_TASKS tareas por carga, saturando los workers
# del Q_CLUSTER en cargas grandes y manteniendo granularidad útil en chicas.
ADMISIONADO_TARGET_TASKS = Q_CLUSTER['workers']
ADMISIONADO_LOTE_MIN = 500
ADMISIONADO_LOTE_MAX = 2500
# Reintentos para deadlocks de SQL Server al llamar a ZEUS — son transitorios
# y la propia respuesta los marca como retry-friendly ("Rerun the transaction").
ADMISIONADO_MAX_RETRIES = 3


# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/zagilad.log'),
            'formatter': 'verbose',
            # En Windows, open() default es cp1252 — sin esto cualquier mensaje
            # con caracteres no-Latin1 (emojis, flechas, '⚠️') crashea el handler
            # silenciosamente y se pierden líneas del log.
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'home': {  # Ajusta esto según el nombre de tu app
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'zeus_mirror': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Manejo de archivos estáticos
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # o la ruta absoluta correcta
MEDIA_URL = '/media/'